GET http://localhost:3000/store

###

GET http://localhost:3000/store/62833965a4a8802f641fd67d


###
POST http://localhost:3000/store HTTP/1.1
content-type: application/json

{
    "name": "PruebaName2",
    "quantity": "PruebaCantidad2",
    "price": "PruebaPrecio2",
    "color": "PruebaColor2",
    "date": "PruebaFecha2"
}


### 
GET https://momsstore.herokuapp.com/store

###
GET https://momsstore.herokuapp.com/store/62833965a4a8802f641fd67d